spring.application.name=chat
spring.datasource.url=mysql://CLICK_TO:REVEAL_PASSWORD@mysql-12321-anmolsah976-d81d.b.aivencloud.com:15989/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=root
spring.datasource.password=Anmol123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=15989

sarvam.api.key==sk_lcuhz6nv_7xysWO8ODFQlCu0BPvpUDfhg
sarvam.model=sarvam-m